version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    depends_on:
      - eureka-server
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - eureka-server
      - rabbitmq
      - zipkin
    networks:
      - backend

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wallet_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - eureka-server
      - rabbitmq
      - zipkin
    networks:
      - backend

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/transaction_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - eureka-server
      - rabbitmq
      - zipkin
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
